services:
  hacofpt-fe:
    container_name: hacofpt-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_REDIRECT_URI=${NEXT_PUBLIC_REDIRECT_URI}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    restart: unless-stopped
    volumes:
      - ./public:/app/public
      # Use anonymous volume for node_modules to avoid overwriting with local node_modules
      - /app/node_modules
    networks:
      - hacofpt-network

# Define a custom network to allow communication between containers
# Useful if you want to add an API container or database later
networks:
  hacofpt-network:
    driver: bridge
